'''
Problem #2 : Even Fibonacci numbers [http://projecteuler.net/problem=2]
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''
#initialize values
a = 0
b = 1
total = 0
value = a + b
# check if the value exceeds 4 million
while value < 4000000:
    # check if the number is even; if so, update total
    if value % 2 ==0 : total = total + value
    #swap values around
    value = a + b
    a = b
    b = value
#print total
print total
